# Generated by Django 5.2.17 on 2026-08-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Natural'), ('SOCIAL', 'Social')], max_length=10, null=True),
        ),
    ]
