# Generated by Django 5.2.17 on 2026-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Addis Ray Secondary School', max_length=200)),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=30)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('current_term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=10)),
                ('passing_mark', models.PositiveSmallIntegerField(default=50)),
                ('attendance_daily', models.BooleanField(default=True)),
                ('ranking_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
