# Generated by Django 5.2.17 on 2026-08-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schoolsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='current_term',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='current_semester',
            field=models.CharField(choices=[('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2')], default='SEMESTER_1', max_length=12),
        ),
    ]
