# Generated by Django 5.2.17 on 2026-08-26 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('father_name', models.CharField(max_length=80)),
                ('grandfather_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=120)),
                ('grade', models.PositiveSmallIntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('hire_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('can_register_students', models.BooleanField(default=False)),
                ('can_take_attendance', models.BooleanField(default=False)),
                ('can_enter_grades', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
