# Generated by Django 5.2.17 on 2026-09-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_graderecord_unique_together_and_more'),
        ('teachers', '0002_teacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profiles', to='academics.subject'),
        ),
    ]
