# Generated by Django 5.2.17 on 2026-08-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade', models.PositiveSmallIntegerField()),
                ('to_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('REPEAT', 'Repeat'), ('COMPLETED', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
            ],
        ),
    ]
