# Generated by Django 5.2.17 on 2026-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10),
        ),
    ]
