# Generated by Django 5.2.17 on 2026-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(default='School Community', max_length=200),
            preserve_default=False,
        ),
    ]
