# Generated by Django 5.2.17 on 2026-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0002_student_stream'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graderecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='semester',
            field=models.CharField(choices=[('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2')], default='SEMESTER_1', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='graderecord',
            unique_together={('student', 'subject', 'academic_year', 'semester')},
        ),
    ]
